services:
  App\Application\Command\User\UserRegistrationHandler:
    arguments:
      - '@App\Persistence\Repository\Doctrine\UserRepository'
      - '@App\Domain\Factory\User\UserFactory'
    public: true
