services:
  App\Api\Controller\RegistrationController:
    arguments:
      - '@App\Infrastructure\CommandBus\ValidationCommandBus'
      - '@App\Infrastructure\QueryBus\SimpleQueryBus'
    tags:
      - { name: controller.service_arguments }
