services:
  App\Infrastructure\Controller\BaseWriteController:
    arguments:
    - '@logger'
    tags:
    - { name: controller.service_arguments }

  App\Api\Controller\RegistrationController:
    arguments:
      - '@App\Application\UseCase\FormValidationRegistration'
    parent: App\Infrastructure\Controller\BaseWriteController
