services:
  App\Infrastructure\Controller\BaseController:
    arguments:
    - '@logger'
    tags:
    - { name: controller.service_arguments }

  App\Api\Controller\RegistrationController:
    arguments:
      - '@App\Application\UseCase\FormValidationRegistration'
    parent: App\Infrastructure\Controller\BaseController

  App\Api\Controller\CheckUniqueEmailController:
    arguments:
    - '@App\Application\UseCase\CheckUniqueEmail'
    parent: App\Infrastructure\Controller\BaseController

  App\Api\Controller\CheckUniqueNickController:
    arguments:
    - '@App\Application\UseCase\CheckUniqueNick'
    parent: App\Infrastructure\Controller\BaseController
