services:
    App\Infrastructure\EventListener\Http\PreflightRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 33 }

    App\Infrastructure\EventListener\Http\JsonDecoderListener:
        arguments:
            - '@logger'
        tags:
        - { name: kernel.event_listener, event: kernel.request }

    App\Infrastructure\EventListener\Http\CORSListener:
        tags:
        - { name: kernel.event_listener, event: kernel.response }

    App\Infrastructure\EventListener\ExceptionsHandling\DomainExceptionListener:
        tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 10 }

    App\Infrastructure\EventListener\ExceptionsHandling\CommandValidationExceptionListener:
        tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 10 }

    App\Infrastructure\EventListener\ExceptionsHandling\InternalExceptionListener:
        arguments:
        - '@logger'
        tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 5 }
