services:
  App\Domain\Factory\User\UserFactory:
    arguments:
      - '@App\Domain\Specification\User\UniqueEmailSpecification'
      - '@App\Domain\Specification\User\UniqueNicknameSpecification'
      - '@App\Persistence\Repository\Doctrine\UserRepository'
      - '@App\Infrastructure\Services\SimplePasswordEncryptor'
