services:

  App\Infrastructure\Form\FormValidationInteractorProxy:
    arguments:
    - '@request_stack'
    - '@form.factory'

  App\Application\UseCase\Registration:
    arguments:
      - '@App\Persistence\Repository\Doctrine\UserRepository'
      - '@App\Domain\Factory\User\UserFactory'

  App\Application\UseCase\FormValidationRegistration:
    class: App\Infrastructure\Form\FormValidationInteractorProxy
    parent: App\Infrastructure\Form\FormValidationInteractorProxy
    arguments:
      - '@App\Application\UseCase\Registration'
      - 'App\Api\HttpForm\Registration'

